name: edb-ansible testing
permissions:
  contents: read
  pull-requests: write
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Execute ansible-lint
    steps:
      - uses: actions/checkout@v2
      - run: |
          docker run --rm -v $(pwd):/data cytopia/ansible-lint playbook.yml
  setup-repo:
    runs-on: ubuntu-22.04
    name: Execute setup_repo tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_repo rocky9
  install-dbserver:
    runs-on: ubuntu-22.04
    name: Execute install_dbserver tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/install_dbserver rocky9
  initdb-dbserver:
    runs-on: ubuntu-22.04
    name: Execute init_dbserver tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/init_dbserver rocky9
  setup-replication:
    runs-on: ubuntu-22.04
    name: Execute setup_replication tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_replication rocky9
  manage-dbserver:
    runs-on: ubuntu-22.04
    name: Execute manage_dbserver tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/manage_dbserver rocky9
  setup-pgpool2:
    runs-on: ubuntu-22.04
    name: Execute setup_pgpool2 tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_pgpool2 rocky9
  manage-pgpool2:
    runs-on: ubuntu-22.04
    name: Execute manage_pgpool2 tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/manage_pgpool2 rocky9
  setup-pgbouncer:
    runs-on: ubuntu-22.04
    name: Execute setup_pgbouncer tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_pgbouncer rocky9
  manage-pgbouncer:
    runs-on: ubuntu-22.04
    name: Execute manage_pgbouncer tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/manage_pgbouncer rocky9
  setup-repmgr:
    runs-on: ubuntu-22.04
    name: Execute setup_repmgr tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_repmgr rocky9
  setup-dbt2-driver:
    runs-on: ubuntu-22.04
    name: Execute setup_dbt2_driver tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_dbt2_driver rocky9
  setup-dbt2-client:
    runs-on: ubuntu-22.04
    name: Execute setup_dbt2_client tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install python3-pip -y
      - run: sudo pip3 install ansible-core
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_dbt2_client rocky9
  setup-dbt2:
    runs-on: ubuntu-22.04
    name: Execute setup_dbt2 tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ansible -y
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_dbt2 rocky9
  setup-dbt3:
    runs-on: ubuntu-22.04
    name: Execute setup_dbt3 tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ansible -y
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_dbt3 rocky9
  setup-dbt7:
    runs-on: ubuntu-22.04
    name: Execute setup_dbt7 tests for PostgreSQL 16 on RockyLinux9
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt install ansible -y
      - run: make
      - run: ANSIBLE_CORE_VERSION=2.14 EDB_PG_TYPE=PG EDB_PG_VERSION=16 EDB_ENABLE_REPO=false make -C tests/cases/setup_dbt7 rocky9
